import os,sys
sys.path.insert(0,os.path.dirname(os.path.abspath(__file__)))
from _common import ROOT, DIST, SP, OUT, serve
exec(open('shots43.py').read().split('errors=[]\nwith')[0].replace('8781','8783'))
errors=[]
def order(pg): return pg.eval_on_selector_all('#home .hblock',"els=>els.filter(e=>getComputedStyle(e).display!=='none').map(e=>e.dataset.hb)")
with sync_playwright() as p:
    b=p.chromium.launch(); ctx=b.new_context(viewport={'width':390,'height':844},device_scale_factor=2,service_workers='block',accept_downloads=True)
    pg=ctx.new_page(); pg.on('pageerror',lambda e: errors.append(str(e)))
    pg.on('console',lambda m: errors.append(m.text) if m.type=='error' and 'TUNNEL' not in m.text else None)
    pg.goto('http://localhost:8783/index.html')
    pg.evaluate("d=>{localStorage.clear();localStorage.setItem('kantong-bersama-v1',JSON.stringify(d));localStorage.setItem('cmoneytracker-tips-seen-v39','1');localStorage.setItem('cmoneytracker-whatsnew-v43','1');localStorage.setItem('cmoneytracker-persist-asked','2026-09-17')}",db)
    pg.reload(); pg.wait_for_timeout(1800)
    print('order awal:',order(pg))
    print('smart hint hidden (banyak data):',pg.is_hidden('#smartHint'),'| alerts head:',pg.is_visible('#alertsHead'))
    print('nudges:',pg.inner_text('#smartNudges').replace('\n',' | ')[:300])
    pg.screenshot(path=OUT+'h1-home.png',full_page=True)
    # backup
    with pg.expect_download() as dl: pg.click('[data-nudge="backup"]')
    pg.wait_for_timeout(400)
    print('backup file:',dl.value.suggested_filename,'| last:',pg.evaluate("localStorage.getItem('cmoneytracker-last-backup')"),'| nudge gone:','backup' not in pg.inner_html('#smartNudges'))
    # atur beranda
    pg.click('#homeCustomize'); pg.wait_for_timeout(300)
    print('sheet rows:',pg.inner_text('#homeLayoutList').replace('\n',' | ')[:200])
    pg.screenshot(path=OUT+'h2-sheet.png')
    pg.click('.switch:has([data-hl-toggle="streaks"])'); pg.wait_for_timeout(200)
    pg.click('[data-hl-move="recent"][data-dir="-1"]'); pg.click('[data-hl-move="recent"][data-dir="-1"]'); pg.wait_for_timeout(200)
    pg.click('#homeSheet [data-close].btn'); pg.wait_for_timeout(200)
    print('order baru:',order(pg),'| saved:',pg.evaluate("JSON.parse(localStorage.getItem('kantong-bersama-v1')).homeLayout"))
    pg.reload(); pg.wait_for_timeout(1500); print('setelah reload:',order(pg))
    pg.click('[data-nav="more"]'); pg.click('#menuCustomize'); pg.click('#homeLayoutReset'); pg.wait_for_timeout(200); pg.click('#homeSheet [data-close].btn')
    pg.click('[data-nav="home"]'); pg.wait_for_timeout(200); print('reset:',order(pg))
    # bantuan
    pg.click('#safeCard [data-help="aman"]'); pg.wait_for_timeout(600)
    print('help page:',pg.is_visible('#help'),'| open:',pg.eval_on_selector_all('.help-item[open]','els=>els.map(e=>e.dataset.helpKey)'))
    pg.screenshot(path=OUT+'h3-help.png')
    pg.fill('#helpSearch','backup'); pg.wait_for_timeout(150)
    print('cari backup:',pg.eval_on_selector_all('.help-item','els=>els.map(e=>e.dataset.helpKey)'))
    pg.fill('#helpSearch','zzzz'); print('kosong:',pg.inner_text('#helpList')[:40])
    pg.evaluate("history.back()"); pg.wait_for_timeout(300)
    pg.click('.tile[data-help="bertahan"]'); pg.wait_for_timeout(400); print('tile help:',pg.eval_on_selector_all('.help-item[open]','els=>els.map(e=>e.dataset.helpKey)'))
    pg.evaluate("history.back()"); pg.click('[data-nav="more"]'); pg.click('#more [data-goto="export"]'); pg.wait_for_timeout(300)
    print('export info:',pg.inner_text('#lastBackupTxt'))
    b.close()
    # pengguna baru: hint tampil, tanpa pengingat backup
    b=p.chromium.launch(); ctx=b.new_context(viewport={'width':390,'height':844},device_scale_factor=2,service_workers='block')
    pg=ctx.new_page(); pg.goto('http://localhost:8783/index.html')
    pg.evaluate("localStorage.clear();localStorage.setItem('kantong-bersama-v1',JSON.stringify({profile:{name:'Budi',total:0,planAt:'2026-09-17'},methodBalances:{Utama:500000}}));localStorage.setItem('cmoneytracker-whatsnew-v43','1')")
    pg.reload(); pg.wait_for_timeout(1500)
    print('baru: hint',pg.is_visible('#smartHint'),'| alerts head',pg.is_visible('#alertsHead'),'| order',order(pg))
    pg.screenshot(path=OUT+'h4-new.png',full_page=True)
    b.close()
srv.terminate()
print('ERRORS:',errors)
