import os,sys
sys.path.insert(0,os.path.dirname(os.path.abspath(__file__)))
from _common import ROOT, DIST, SP, OUT, serve
import subprocess,time,json
from playwright.sync_api import sync_playwright

srv=serve(8776)
errors=[]
def st(pg): return pg.evaluate("JSON.parse(localStorage.getItem('kantong-bersama-v1')||'null')")
with sync_playwright() as p:
    b=p.chromium.launch(); ctx=b.new_context(viewport={'width':390,'height':844},device_scale_factor=2,service_workers='block')
    pg=ctx.new_page(); pg.on('pageerror',lambda e: errors.append(str(e)))
    pg.on('console',lambda m: errors.append(m.text) if m.type=='error' and 'TUNNEL' not in m.text else None)
    pg.goto('http://localhost:8776/index.html'); pg.evaluate("localStorage.clear()"); pg.reload(); pg.wait_for_timeout(2800)
    print('onboard visible:',pg.is_visible('#onboard'),'tips hidden:',pg.is_hidden('#tipsModal'))
    pg.screenshot(path=OUT+'o0.png')
    pg.click('#obNext'); print('err empty name:',pg.inner_text('#obErr'))
    pg.fill('#obName','Rina'); pg.click('#obNext'); pg.wait_for_timeout(150)
    pg.fill('#obSaldo','3500000'); pg.dispatch_event('#obSaldo','input'); pg.screenshot(path=OUT+'o1.png'); pg.click('#obNext')
    pg.click('#obNext'); print('err inc:',pg.inner_text('#obErr'))
    pg.click('[data-inc="gaji"]'); pg.fill('#obIncome','6000000'); pg.dispatch_event('#obIncome','input'); pg.fill('#obPayday','25')
    pg.screenshot(path=OUT+'o2.png'); pg.click('#obNext')
    pg.click('[data-fx="Kos"]'); pg.click('#obNext'); print('err fixed:',pg.inner_text('#obErr'))
    pg.fill('[data-fx-amt="Kos"]','1500000'); pg.dispatch_event('[data-fx-amt="Kos"]','input'); pg.fill('[data-fx-day="Kos"]','1'); pg.dispatch_event('[data-fx-day="Kos"]','input')
    pg.click('[data-fx="Cicilan"]'); pg.fill('[data-fx-amt="Cicilan"]','500000'); pg.dispatch_event('[data-fx-amt="Cicilan"]','input'); pg.fill('[data-fx-day="Cicilan"]','28'); pg.dispatch_event('[data-fx-day="Cicilan"]','input')
    print('fixed sum:',pg.inner_text('#obFixedSum'))
    pg.screenshot(path=OUT+'o3.png'); pg.click('#obNext')
    pg.click('#obNext'); print('err goal:',pg.inner_text('#obErr'))
    pg.click('[data-goal="beli"]'); pg.click('#obNext'); print('err beli:',pg.inner_text('#obErr'))
    pg.fill('[data-gx="name"]','Laptop'); pg.dispatch_event('[data-gx="name"]','input')
    pg.fill('[data-gx="price"]','9000000'); pg.dispatch_event('[data-gx="price"]','input')
    pg.fill('[data-gx="months"]','10'); pg.dispatch_event('[data-gx="months"]','input')
    pg.screenshot(path=OUT+'o4.png'); pg.click('#obNext'); pg.wait_for_timeout(200)
    print('plan:',pg.inner_text('#obPlan').replace('\n',' | ')[:700])
    pg.screenshot(path=OUT+'o5.png',full_page=True)
    pg.eval_on_selector('#onboard .sheet','e=>e.scrollTop=9999'); pg.screenshot(path=OUT+'o5b.png')
    pg.click('#obNext'); pg.wait_for_timeout(3200)
    d=st(pg)
    print('profile:',d['profile'],'payday',d['payday'],'budget',d['monthlyBudget'],'saldo base',d['methodBalances'])
    print('tpl:',[(t['category'],t['amount'],t['dayOfMonth'],t.get('skip')) for t in d['recurringTemplates']],'exp:',len(d['expenses']),'custom',d['customCategories'],d['categoryClass'])
    print('wish:',d['wishes'])
    print('home saldo:',pg.inner_text('#saldoTersedia'),'| safe:',pg.inner_text('#safeToday'),'| nudges:',pg.inner_text('#smartNudges').replace('\n',' '))
    pg.screenshot(path=OUT+'o6-home.png')
    pg.click('#healthPill'); pg.wait_for_timeout(300)
    print('goal card:',pg.inner_text('#goalCard').replace('\n',' | '))
    print('findings:',pg.eval_on_selector_all('#adviceList .advice-card','els=>els.map(e=>e.querySelector("div > b").textContent)'))
    pg.screenshot(path=OUT+'o7-advice.png')
    pg.click('#goalCard [data-sim-open]'); pg.wait_for_timeout(300)
    print('sim tab:',pg.eval_on_selector('#simTabs .on','e=>e.dataset.sim'),'| target prefilled:',pg.input_value('#stName'),pg.input_value('#stTarget'),pg.input_value('#stMonths'))
    print('sim target:',pg.inner_text('#simResult').replace('\n',' | ')[:500])
    pg.screenshot(path=OUT+'o8-sim-target.png',full_page=True)
    # add some expenses to have data, then hemat
    pg.evaluate("""(()=>{const d=JSON.parse(localStorage.getItem('kantong-bersama-v1'));const t=new Date();for(let i=1;i<=t.getDate();i++){const ds=t.getFullYear()+'-'+String(t.getMonth()+1).padStart(2,'0')+'-'+String(i).padStart(2,'0');d.expenses.push({id:'1700000000'+i+'1',date:ds,type:'daily',category:'Makan & minum',note:'',amount:45000});if(i%3==0)d.expenses.push({id:'1700000000'+i+'2',date:ds,type:'recurring',category:'Jajan',note:'boba',amount:35000})}localStorage.setItem('kantong-bersama-v1',JSON.stringify(d))})()""")
    pg.reload(); pg.wait_for_timeout(2800)
    pg.click('[data-nav="more"]'); pg.click('#more [data-goto="sim"]'); pg.wait_for_timeout(300)
    print('base:',pg.inner_text('#simBaseTxt'))
    print('cut rows:',pg.inner_text('#simCutRows').replace('\n',' | '))
    pg.eval_on_selector('[data-cut="Jajan"]',"e=>{e.value=50;e.dispatchEvent(new Event('input',{bubbles:true}))}")
    print('hemat:',pg.inner_text('#simResult').replace('\n',' | ')[:500])
    pg.screenshot(path=OUT+'o9-sim-hemat.png',full_page=True)
    pg.click('[data-sim="beli"]'); pg.fill('#sbName','HP'); pg.fill('#sbPrice','8000000'); pg.dispatch_event('#sbPrice','input')
    print('beli tunai:',pg.inner_text('#simResult').replace('\n',' | ')[:300])
    pg.click('[data-mode="cicil"]'); pg.wait_for_timeout(100)
    print('beli cicil:',pg.inner_text('#simResult').replace('\n',' | ')[:500])
    pg.screenshot(path=OUT+'o10-sim-beli.png',full_page=True)
    pg.click('[data-sim="darurat"]'); print('darurat:',pg.inner_text('#simResult').replace('\n',' | ')[:400])
    pg.click('[data-sim="utang"]'); pg.fill('#suTotal','5000000'); pg.dispatch_event('#suTotal','input'); pg.fill('#suPay','300000'); pg.dispatch_event('#suPay','input')
    pg.eval_on_selector('#suExtra',"e=>{e.value=200000;e.dispatchEvent(new Event('input',{bubbles:true}))}")
    print('utang:',pg.inner_text('#simResult').replace('\n',' | ')[:500])
    pg.screenshot(path=OUT+'o11-sim-utang.png',full_page=True)
    # claude prompt capture
    urls=[]
    ctx.route('https://claude.ai/**',lambda r: (urls.append(r.request.url),r.abort()))
    pg.click('#simAskClaude'); pg.wait_for_timeout(800)
    import urllib.parse
    q=urllib.parse.unquote(urls[0].split('q=',1)[1]) if urls and 'q=' in urls[0] else ''
    print('claude url:',len(urls),'has sim:','SIMULASI' in q,'| profil:',q[q.find('PROFIL'):q.find('PROFIL')+260].replace('\n',' / ') if 'PROFIL' in q else '')
    b.close()
srv.terminate()
print('ERRORS:',errors)
