import os,sys
sys.path.insert(0,os.path.dirname(os.path.abspath(__file__)))
from _common import ROOT, DIST, SP, OUT, serve
exec(open('test8.py').read().split("errors=[]")[0].replace('8774','8778'))
import datetime as _dt
errors=[]
def S(pg): return pg.evaluate("JSON.parse(localStorage.getItem('kantong-bersama-v1'))")
with sync_playwright() as p:
    b=p.chromium.launch(); ctx=b.new_context(viewport={'width':390,'height':844},device_scale_factor=2,service_workers='block')
    pg=ctx.new_page(); pg.on('pageerror',lambda e: errors.append(str(e)))
    pg.on('console',lambda m: errors.append(m.text) if m.type=='error' and 'TUNNEL' not in m.text else None)
    pg.goto('http://localhost:8778/index.html')
    db['profile']['incomeMonthly']=6000000; db['profile']['planAt']='2026-06-01'; db['monthlyBudget']=4000000
    pg.evaluate("d=>{localStorage.clear();localStorage.setItem('kantong-bersama-v1',JSON.stringify(d));localStorage.setItem('cmoneytracker-tips-seen-v39','1');localStorage.setItem('cmoneytracker-whatsnew-v43','1')}",db)
    pg.reload(); pg.wait_for_timeout(1500)
    d=S(pg); print('snap months:',list(d['planSnap'].keys()),d['planSnap'].get(t.isoformat()[:7]))
    print('export meta:',pg.inner_text('#menuExportMeta'))
    pg.click('[data-nav="more"]'); pg.click('#more [data-goto="export"]'); pg.wait_for_timeout(300)
    print('persist card:',pg.inner_text('#persistCard').replace('\n',' | '))
    pg.screenshot(path=OUT+'r-persist.png')
    pg.click('#persistBtn') if pg.is_visible('#persistBtn') else None; pg.wait_for_timeout(400)
    print('after click:',pg.inner_text('#persistState').replace('\n',' '),'| toast:',pg.inner_text('#undoToastMsg'))
    pg.evaluate("history.back()"); pg.wait_for_timeout(200)
    pg.click('#more [data-goto="review"]'); pg.wait_for_timeout(400)
    print('review month:',pg.inner_text('#revMonth'))
    print('grade:',pg.inner_text('#revGrade').replace('\n',' | '))
    print('rows:',pg.inner_text('#revRows').replace('\n',' | ')[:500])
    print('notes:',pg.inner_text('#revNotes').replace('\n',' | '))
    print('sugs:',pg.inner_text('#revSugs').replace('\n',' | '))
    pg.screenshot(path=OUT+'r-cur.png',full_page=True)
    pg.click('#revPrev'); pg.wait_for_timeout(300)
    print('prev month:',pg.inner_text('#revMonth'),'|',pg.inner_text('#revGrade').replace('\n',' | ')[:120])
    print('prev notes:',pg.inner_text('#revNotes').replace('\n',' | '))
    print('prev sugs:',pg.inner_text('#revSugs').replace('\n',' | '))
    pg.screenshot(path=OUT+'r-prev.png',full_page=True)
    btn=pg.query_selector('[data-rev-apply^="budget"]')
    if btn:
        act=btn.get_attribute('data-rev-apply'); btn.click(); pg.wait_for_timeout(300)
        print('applied',act,'->',S(pg)['monthlyBudget'],'| toast:',pg.inner_text('#undoToastMsg'))
        pg.click('#undoBtn'); pg.wait_for_timeout(300); print('undo ->',S(pg)['monthlyBudget'])
    btn=pg.query_selector('[data-rev-apply^="cap"]')
    if btn: act=btn.get_attribute('data-rev-apply'); btn.click(); pg.wait_for_timeout(300); print('applied',act,S(pg)['categoryBudgets'])
    print('snap after apply:',S(pg)['planSnap'][t.isoformat()[:7]]['caps'])
    b.close()
    # awal bulan berikutnya → ajakan evaluasi
    b=p.chromium.launch(); ctx=b.new_context(viewport={'width':390,'height':844},device_scale_factor=2,service_workers='block')
    pg=ctx.new_page(); pg.on('pageerror',lambda e: errors.append(str(e)))
    nm=_dt.datetime(t.year+(t.month==12),(t.month%12)+1,3,9,0)
    pg.clock.install(time=nm)
    pg.goto('http://localhost:8778/index.html')
    pg.evaluate("d=>{localStorage.clear();localStorage.setItem('kantong-bersama-v1',JSON.stringify(d));localStorage.setItem('cmoneytracker-tips-seen-v39','1');localStorage.setItem('cmoneytracker-whatsnew-v43','1')}",db)
    pg.reload(); pg.wait_for_timeout(1500)
    print('next-month nudges:',pg.inner_text('#smartNudges').replace('\n',' | '))
    pg.click('[data-nudge^="review:"]'); pg.wait_for_timeout(400)
    print('opened:',pg.is_visible('#review'),pg.inner_text('#revMonth'),'| snap keys',list(S(pg)['planSnap'].keys()))
    print('grade:',pg.inner_text('#revGrade').replace('\n',' | ')[:150])
    pg.click('[data-nav="home"]'); pg.wait_for_timeout(300)
    print('nudge gone:','Evaluasi' not in pg.inner_text('#smartNudges'))
    b.close()
srv.terminate()
print('ERRORS:',errors)
