import os,sys
sys.path.insert(0,os.path.dirname(os.path.abspath(__file__)))
from _common import ROOT, DIST, SP, OUT, serve
exec(open('test8.py').read().split("errors=[]")[0].replace('8774','8777'))
errors=[]
with sync_playwright() as p:
    b=p.chromium.launch(); ctx=b.new_context(viewport={'width':390,'height':844},device_scale_factor=2,service_workers='block')
    pg=ctx.new_page(); pg.on('pageerror',lambda e: errors.append(str(e)))
    pg.goto('http://localhost:8777/index.html')
    pg.evaluate("d=>{d.recurringTemplates=[{id:'t1',category:'Internet',amount:300000,dayOfMonth:20,note:''}];localStorage.clear();localStorage.setItem('kantong-bersama-v1',JSON.stringify(d));localStorage.setItem('cmoneytracker-tips-seen-v39','1');localStorage.setItem('cmoneytracker-whatsnew-v43','1')}",db)
    pg.reload(); pg.wait_for_timeout(1500)
    print('onboard hidden for existing:',pg.is_hidden('#onboard'))
    print('plan nudge:', 'Lengkapi rencana' in pg.inner_text('#smartNudges'))
    pg.click('#healthPill'); pg.wait_for_timeout(200); print('empty goal card:',pg.inner_text('#goalCard').replace('\n',' | '))
    pg.click('[data-nav="more"]'); pg.click('#menuPlan'); pg.wait_for_timeout(300)
    print('prefill name:',pg.input_value('#obName'),'back text:',pg.inner_text('#obBack'))
    pg.click('#obNext'); print('saldo prefill:',pg.input_value('#obSaldo'),'|',pg.inner_text('#obSaldoNote'))
    pg.click('#obNext'); print('inc prefill:',pg.eval_on_selector('#obIncType .on','e=>e.dataset.inc'),pg.input_value('#obIncome'))
    pg.click('#obNext'); print('fixed:',pg.inner_text('#obFixed').replace('\n',' | ')[:200])
    pg.screenshot(path=OUT+'p-fixed.png')
    pg.click('#obNext')
    for goal in ['darurat','utang','hemat','investasi']:
        pg.click('[data-goal="%s"]'%goal); pg.wait_for_timeout(100)
        if goal=='utang':
            pg.fill('[data-gx="debtTotal"]','4000000'); pg.dispatch_event('[data-gx="debtTotal"]','input')
            pg.fill('[data-gx="debtPay"]','500000'); pg.dispatch_event('[data-gx="debtPay"]','input')
        pg.click('#obNext'); pg.wait_for_timeout(150)
        print(goal,'plan:',pg.inner_text('#obPlan').replace('\n',' | ')[-260:])
        pg.click('#obNext'); pg.wait_for_timeout(400)
        pg.click('[data-nav="home"]'); pg.click('#healthPill'); pg.wait_for_timeout(200)
        print(goal,'card:',pg.inner_text('#goalCard').replace('\n',' | ')[:330])
        print('   home strip:',pg.is_visible('#homeGoal'))
        pg.screenshot(path=OUT+'p-'+goal+'.png')
        pg.click('#goalCard [data-plan-open]'); pg.wait_for_timeout(250)
    pg.click('#obBack'); pg.click('#obBack'); pg.wait_for_timeout(100)
    d=pg.evaluate("JSON.parse(localStorage.getItem('kantong-bersama-v1'))")
    print('templates:',len(d['recurringTemplates']),'expenses before/after same?',len(d['expenses']),'budget kept:',d.get('monthlyBudget'))
    b.close()
srv.terminate()
print('ERRORS:',errors)
