import os,sys
sys.path.insert(0,os.path.dirname(os.path.abspath(__file__)))
from _common import ROOT, DIST, SP, OUT, serve
import json, random, datetime, subprocess, time
from playwright.sync_api import sync_playwright

srv=serve(8772)
src=open('test2.py').read(); ns={}
random.seed(3); today=datetime.date.today()
exec(src[src.index('def mk'):src.index('scenarios=')],{'random':random,'datetime':datetime,'today':today},ns)
db=ns['mk']()
FAKE="""window.webkitSpeechRecognition=class{start(){setTimeout(()=>{this.onresult&&this.onresult({results:[Object.assign([{transcript:'kopi dua puluh ribu'}],{isFinal:true})]});setTimeout(()=>this.onend&&this.onend(),50)},100)}stop(){this.onend&&this.onend()}};window.SpeechRecognition=window.webkitSpeechRecognition;"""
errors=[]
def st(pg): return pg.evaluate("JSON.parse(localStorage.getItem('kantong-bersama-v1'))")
def more(pg,goto):
    pg.click('[data-nav="more"]'); pg.wait_for_timeout(150); pg.click(f'#more [data-goto="{goto}"]'); pg.wait_for_timeout(300)
with sync_playwright() as p:
    b=p.chromium.launch()
    ctx=b.new_context(viewport={'width':390,'height':844},device_scale_factor=2,service_workers='block',has_touch=True)
    ctx.add_init_script(FAKE)
    pg=ctx.new_page()
    pg.on('pageerror',lambda e: errors.append(str(e)))
    pg.on('console',lambda m: errors.append(m.text) if m.type=='error' and 'TUNNEL' not in m.text else None)
    pg.goto('http://localhost:8772/index.html')
    pg.evaluate("d=>{localStorage.clear();localStorage.setItem('kantong-bersama-v1',JSON.stringify(d));localStorage.setItem('cmoneytracker-tips-seen-v39','1')}",db)
    pg.reload(); pg.wait_for_timeout(2200)
    print('news sheet for existing user:',pg.is_visible('#newsSheet'))
    pg.screenshot(path=OUT+'f-news.png')
    pg.click('#newsSheet [data-close].btn'); pg.wait_for_timeout(200)
    print('home level chip:',pg.inner_text('#homeLevel'))
    # payday
    pd=(today+datetime.timedelta(days=9)).day
    pg.click('[data-nav="more"]'); pg.click('#paydayOpen'); pg.fill('#paydayInput',str(pd)); pg.click('#paydaySave'); pg.wait_for_timeout(300)
    pg.click('[data-nav="home"]'); pg.wait_for_timeout(300)
    print('payday line:',pg.inner_text('#safePayday'),'| hint:',pg.inner_text('#safeHint')[:90])
    pg.screenshot(path=OUT+'f-home.png')
    pg.click('[data-nav="more"]'); pg.click('#paydayOpen'); pg.fill('#paydayInput',str(today.day)); pg.click('#paydaySave'); pg.wait_for_timeout(300)
    pg.click('[data-nav="home"]'); print('payday today:',pg.inner_text('#safePayday'))
    # subs
    more(pg,'subs')
    pg.click('[data-sub-preset="Spotify"]'); pg.wait_for_timeout(300); pg.fill('#subAmount','54990'); pg.fill('#subDay',str(min(today.day,28))); pg.click('#subSave'); pg.wait_for_timeout(300)
    pg.click('[data-sub-preset="iCloud"]'); pg.wait_for_timeout(300); pg.fill('#subAmount','150000'); pg.click('[data-cycle="yearly"]'); pg.select_option('#subMonth',str(today.month)); pg.fill('#subDay',str(min(today.day,28))); pg.click('#subSave'); pg.wait_for_timeout(300)
    pg.click('[data-sub-preset="Netflix"]'); pg.wait_for_timeout(300); pg.fill('#subAmount','65000'); pg.fill('#subDay','28'); pg.click('#subSave'); pg.wait_for_timeout(300)
    s=st(pg); print('subs posted:',[(x['note'],x['amount']) for x in s['expenses'] if x.get('category')=='Langganan'])
    pg.click('[data-sub-rare] >> nth=2'); pg.wait_for_timeout(200)
    print('sub totals:',pg.inner_text('#subPerMonth'),pg.inner_text('#subPerYear'),'|',pg.inner_text('#subRareNote'))
    pg.screenshot(path=OUT+'f-subs.png',full_page=True)
    pg.click('#subs [data-back]'); more(pg,'bills'); print('bills list excludes subs:','Spotify' not in pg.inner_text('#recurringTemplateList'))
    pg.click('#bills [data-back]')
    # wishlist
    more(pg,'wishlist')
    pg.click('#addWishBtn'); pg.fill('#wishName','iPhone baru'); pg.fill('#wishPrice','15000000'); pg.set_input_files('#wishPhoto',os.path.join(os.path.dirname(os.path.abspath(__file__)),'fixtures','phone.jpg')); pg.wait_for_timeout(500); pg.click('#wishSave'); pg.wait_for_timeout(300)
    pg.click('#addWishBtn'); pg.fill('#wishName','Sepatu lari'); pg.fill('#wishPrice','900000'); pg.click('[data-wish-emoji="👟"]'); pg.click('#wishSave'); pg.wait_for_timeout(300)
    print('wish list:',pg.inner_text('#wishList').replace('\n',' | ')[:260])
    pg.screenshot(path=OUT+'f-wish.png',full_page=True)
    pg.click('[data-wish] >> nth=1'); pg.wait_for_timeout(300); print('plan txt:',pg.inner_text('#wishPlanTxt')[:120])
    pg.click('#wishTopBtn'); pg.wait_for_timeout(300)
    print('order after top:',[w['name'] for w in st(pg)['wishes']])
    pg.click('[data-wish] >> nth=0'); pg.wait_for_timeout(300); pg.click('#wishBoughtBtn'); pg.wait_for_timeout(600)
    s=st(pg); print('wish done:',[(w['name'],w['done']) for w in s['wishes']],'expense:',s['expenses'][-1]['note'],'badge wish:', 'wish' in s['badges'])
    pg.click('#wishlist [data-back]')
    # challenges
    more(pg,'game')
    for k in ['nokopi','masak','hemat','weekend']: pg.click(f'[data-ch-start="{k}"]'); pg.wait_for_timeout(200)
    pg.click('[data-ch-check]'); pg.wait_for_timeout(200)
    print('active:',pg.inner_text('#chActive').replace('\n',' | ')[:300])
    pg.screenshot(path=OUT+'f-game.png',full_page=True)
    pg.click('[data-nav="home"]'); pg.click('#micBtn'); pg.wait_for_timeout(1000)
    s=st(pg); print('after kopi voice, nokopi status:',[c['status'] for c in s['challenges'] if c['type']=='nokopi'],'badges:',list(s['badges'].keys()))
    # events
    more(pg,'events')
    pg.click('#addEventBtn'); pg.fill('#evName','Trip Bali'); pg.fill('#evBudget','1000000'); pg.fill('#evMembers','Andi, Budi'); pg.click('#evSave'); pg.wait_for_timeout(300)
    pg.click('[data-nav="home"]'); pg.wait_for_timeout(300); print('event banner:',pg.inner_text('#eventBanner').replace('\n',' | '))
    s0=pg.evaluate("()=>{}")
    pg.click('#fabAdd'); pg.wait_for_timeout(400); print('sheet event chip:',pg.inner_text('#sheetEventChip'),pg.get_attribute('#sheetEventChip','class'))
    pg.screenshot(path=OUT+'f-sheet-event.png')
    pg.fill('#sheetAmount','300000'); pg.click('[data-sheet-cat="Makan & minum"]'); pg.click('#sheetSave'); pg.wait_for_timeout(300)
    pg.fill('#smartQuickInput','parkir 10rb'); pg.press('#smartQuickInput','Enter'); pg.wait_for_timeout(300)
    s=st(pg); ev=s['events'][0]['id']; print('tagged:',[(x['category'],x['amount']) for x in s['expenses'] if x.get('eventId')==ev])
    pg.wait_for_timeout(700); sal1=pg.inner_text('#saldoTersedia')
    pg.click('#eventBanner'); pg.wait_for_timeout(300); print('event detail:',pg.inner_text('#evDetailSpent'),'|',pg.inner_text('#evSplitInfo')[:100])
    pg.screenshot(path=OUT+'f-event.png')
    pg.click('#evSplitBtn'); pg.wait_for_timeout(1000); sal2=pg.inner_text('#saldoTersedia')
    s=st(pg); print('split debts:',[(d['person'],d['amount'],d['moves']) for d in s['debts']],'saldo',sal1,'->',sal2)
    more(pg,'debts'); pg.click('[data-debt] >> nth=0'); pg.wait_for_timeout(300); pg.click('#settleBtn'); pg.wait_for_timeout(300); pg.click('#debtClose')
    pg.click('#debts [data-back]'); pg.click('[data-nav="home"]'); pg.wait_for_timeout(900); print('saldo after 1 repay:',pg.inner_text('#saldoTersedia'))
    # roast
    pg.click('#healthPill'); pg.wait_for_timeout(300); pg.click('[data-cmode="roast"]'); pg.wait_for_timeout(200)
    print('roast prompt:',pg.eval_on_selector('#claudePreview','e=>e.textContent')[:60],'| btn:',pg.inner_text('#askClaudeBtn'))
    pg.click('#advice [data-back]')
    # accent
    pg.click('[data-nav="more"]'); pg.click('[data-accent-pick="pink"]'); pg.wait_for_timeout(200)
    pg.reload(); pg.wait_for_timeout(1500); print('accent persisted:',pg.evaluate("document.documentElement.dataset.accent"))
    pg.screenshot(path=OUT+'f-pink.png')
    # swipe delete via CDP touch
    pg.click('[data-nav="tx"]'); pg.wait_for_timeout(400)
    n0=len(st(pg)['expenses'])+len(st(pg)['incomes'])
    box=pg.locator('#monthlyList .tx >> nth=0').bounding_box()
    cdp=ctx.new_cdp_session(pg); y=box['y']+box['height']/2; x=box['x']+box['width']-20
    cdp.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[{'x':x,'y':y}]})
    for k in range(1,9): cdp.send('Input.dispatchTouchEvent',{'type':'touchMove','touchPoints':[{'x':x-k*20,'y':y+1}]})
    cdp.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]}); pg.wait_for_timeout(500)
    n1=len(st(pg)['expenses'])+len(st(pg)['incomes'])
    print('swipe delete:',n0,'->',n1,'sheet open?',pg.is_visible('#txSheet'))
    # recap brag button (CDN blocked -> toast)
    pg.click('[data-nav="more"]'); pg.click('#menuRecap'); pg.wait_for_timeout(500); pg.click('#recapBrag'); pg.wait_for_timeout(1500); print('brag toast:',pg.inner_text('#undoToastMsg'))
    n=pg.locator('#recapTrack .rc').count(); print('recap cards:',n)
    pg.screenshot(path=OUT+'f-recap.png')
    pg.click('#recapClose')
    # shortcuts
    p2=ctx.new_page(); p2.on('pageerror',lambda e: errors.append('p2 '+str(e)))
    p2.goto('http://localhost:8772/index.html?action=add'); p2.wait_for_timeout(1800)
    print('shortcut add -> sheet:',p2.is_visible('#txSheet'),'url:',p2.url)
    p3=ctx.new_page(); p3.goto('http://localhost:8772/index.html?action=voice'); p3.wait_for_timeout(2500)
    print('shortcut voice -> last exp:',p3.evaluate("(()=>{const a=JSON.parse(localStorage.getItem('kantong-bersama-v1')).expenses;return a[a.length-1].note+' '+a[a.length-1].amount})()"))
    b.close()
srv.terminate()
print('ERRORS:',errors)
